### ISSUE TITLE
commonj.connector.runtime.DataBindingException

### ISSUE THREAD

**Issue by shaffigithub** [foundweekends/giter8#120]
commonj.connector.runtime.DataBindingException: java.nio.charset.MalformedInputException: Input length = 1.
Caused By: commonj.connector.runtime.DataBindingException: java.nio.charset.MalformedInputException: Input length = 1
    at com.ibm.wsspi.sca.mq.data.MQParsableNativeDataHolder.getBody(MQParsableNativeDataHolder.java:217)
    at com.ibm.wsspi.sca.mq.inbound.MQInboundImpl.onMessage(MQInboundImpl.java:374)
    at com.ibm.ejs.jms.listener.MDBWrapper$PriviledgedOnMessage.run(MDBWrapper.java:302)

**Comment by eed3si9n** [comment]
Could you post reproduction steps for this problem?
