### ISSUE TITLE
Public Repo - Exception caught during execution of fetch command

### ISSUE THREAD

**Issue by film42** [foundweekends/giter8#122]
Just tried `g8 fayimora/basic-scala-project` which is one of the public templates in the wiki and the error occurred.

Stack-trace:

```
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of fetch command
    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:138)
    at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:175)
    at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:121)
    at giter8.Apply$class.clone(apply.scala:73)
    at giter8.Giter8.clone(giter8.scala:3)
    at giter8.Apply$class.inspect(apply.scala:33)
    at giter8.Giter8.inspect(giter8.scala:3)
    at giter8.Apply$class.inspect(apply.scala:55)
    at giter8.Giter8.inspect(giter8.scala:3)
    at giter8.Giter8$$anonfun$2.apply(giter8.scala:19)
    at giter8.Giter8$$anonfun$2.apply(giter8.scala:18)
    at scala.Option.map(Option.scala:133)
    at giter8.Giter8.run(giter8.scala:18)
    at giter8.Giter8.run(giter8.scala:10)
    at giter8.Giter8.run(giter8.scala:3)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
    at xsbt.boot.Launch$.run(Launch.scala:57)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:65)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:32)
    at xsbt.boot.Boot$.main(Boot.scala:21)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:fayimora/basic-scala-project.g8.git: unknown host
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:138)
    at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121)
    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:248)
    at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
    at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:127)
    at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:113)
    at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1062)
    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:129)
    ... 23 more
Error during sbt execution: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of fetch command
```

**Comment by alinaboghiu** [comment]
Same problem. I checked my ssh connection to github and it seems fine.

**Comment by eed3si9n** [comment]
Works for me using the latest version of Giter8.
