### ISSUE TITLE
Throw error if the template contains the `sbt` shell

### ISSUE THREAD

**Issue by freewind** [foundweekends/giter8#158]
In my template, there is a `sbt` shell file, the content is exactly the same as <https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt>, which contains a lot of `$`, e.g.:

```
#!/usr/bin/env bash
#
# A more capable sbt runner, coincidentally also called sbt.
# Author: Paul Phillips <paulp@improving.org>

# todo - make this dynamic
declare -r sbt_release_version="0.13.8"
declare -r sbt_unreleased_version="0.13.8"
declare -r buildProps="project/build.properties"

declare sbt_jar sbt_dir sbt_create sbt_version
declare scala_version sbt_explicit_version
declare verbose noshare batch trace_level log_level
declare sbt_saved_stty debugUs

echoerr () { echo >&2 "$@"; }
vlog ()    { [[ -n "$verbose" ]] && echoerr "$@"; }

# spaces are possible, e.g. sbt.version = 0.13.0
build_props_sbt () {
  [[ -r "$buildProps" ]] && \
    grep '^sbt\.version' "$buildProps" | tr '=\r' ' ' | awk '{ print $2; }'
}

update_build_props_sbt () {
```

When I run `g8` on it, it will report errors:

```
16:25: '"; }
vlog ()    { [[ -n "' came as a complete surprise to me
org.stringtemplate.v4.compiler.STException
	at org.stringtemplate.v4.compiler.Compiler.reportMessageAndThrowSTException(Compiler.java:213)
	at org.stringtemplate.v4.compiler.Compiler.compile(Compiler.java:143)
	at org.stringtemplate.v4.STGroup.compile(STGroup.java:448)
	at org.stringtemplate.v4.ST.<init>(ST.java:173)
	at org.clapper.scalasti.STHelper$.apply(ScalastiHelper.scala:8)
	at giter8.G8$.applyTemplate(g8.scala:43)
```

How to fix it?

**Comment by ches** [comment]
A small mention in the README:

> The `verbatim` field, if defined, is assumed to be the space delimited list of file patterns such as `*.html *.js`. Files matching `verbatim` pattern are excluded from string template processing.

That refers to the `default.properties` file for your template. So I believe matching on "sbt" with no globbing wildcard would solve this for you:

```
verbatim = sbt .DS_Store *.swp
```

(See also #123 for a caveat.)

**Comment by freewind** [comment]
@ches :+1:
