### ISSUE TITLE
scala.MatchError when working with private repo

### ISSUE THREAD

**Issue by realstraw** [foundweekends/giter8#163]
Installed g8 with homebrew, works fine with public repos, but when I make my repo private, it shows the following error message.

```
$ g8 myprivate/repo.g8.git
scala.MatchError: org.eclipse.jgit.transport.CredentialItem$StringType@565f390 (of class org.eclipse.jgit.transport.CredentialItem$StringType)
    at giter8.ConsoleCredentialsProvider$$anonfun$get$1.apply(apply.scala:134)
    at giter8.ConsoleCredentialsProvider$$anonfun$get$1.apply(apply.scala:134)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
    at giter8.ConsoleCredentialsProvider$.get(apply.scala:134)
    at giter8.ConsoleCredentialsProvider$.get(apply.scala:127)
    at org.eclipse.jgit.transport.CredentialsProviderUserInfo.promptPassphrase(CredentialsProviderUserInfo.java:98)
    at com.jcraft.jsch.UserAuthPublicKey.start(UserAuthPublicKey.java:116)
    at com.jcraft.jsch.Session.connect(Session.java:425)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
    at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121)
    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:248)
    at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
    at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:127)
    at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:113)
    at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1062)
    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:129)
    at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:175)
    at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:121)
    at giter8.Apply$class.clone(apply.scala:95)
    at giter8.Giter8.clone(giter8.scala:3)
    at giter8.Apply$class.inspect(apply.scala:54)
    at giter8.Giter8.inspect(giter8.scala:3)
    at giter8.Giter8$$anonfun$2.apply(giter8.scala:22)
    at giter8.Giter8$$anonfun$2.apply(giter8.scala:18)
    at scala.Option.map(Option.scala:145)
    at giter8.Giter8.run(giter8.scala:18)
    at giter8.Giter8$.main(giter8.scala:92)
    at giter8.Giter8.main(giter8.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at xsbt.boot.PlainApplication.run(PlainApplication.scala:18)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: scala.MatchError: org.eclipse.jgit.transport.CredentialItem$StringType@565f390 (of class org.eclipse.jgit.transport.CredentialItem$StringType)
```

**Comment by gloomypenguin** [comment]
This is happening to me with eed3si9n/scalaxb currently.  Any movement?

**Comment by paulCodes** [comment]
same exception for me. I can clone the repo the  ```g8 file://myrepo.g8`` and able to use it.

**Comment by padilo** [comment]
Are you using a ssh certificate with password?
I had the same problem and I solved in PR #169

**Comment by padilo** [comment]
@paulCodes, @gloomypenguin are you still having this problem? Maybe your ssh certificates are password protected?

**Comment by paulCodes** [comment]
Thanks, @padilo will take a look and see if this works for me.

**Comment by gloomypenguin** [comment]
my ssh is password protected.... how do we install/upgrade to 0.6.9?

**Comment by padilo** [comment]
@gloomypenguin You can install the version with this corrected following this: https://github.com/n8han/conscript#readme over my fork: https://github.com/padilo/giter8

nice @paulCodes :+1: 

If do you need help to test my forked version I can send you exactly what do to ;)

**Comment by gloomypenguin** [comment]
I totally did that but got some errors. I'll try again tomorrow.  I already
did a massive work around a while ago but I'd like this to work in a
straight forward way.  OSX, btw.

**Comment by TheIcemanCometh** [comment]
@padilo - I just installed your patched version and I'm still getting the same errors.  Any ideas?
