### ISSUE TITLE
g8 substitution failing in other uses of '$'

### ISSUE THREAD

**Issue by billstephens** [foundweekends/giter8#212]
I'm tempting a JSON file that includes a placeholder for version (${version}).  It seems that g8 is matching on the first '$' but gets confused 

Example: some items removed
{
   "artifactId":"$name$",
  "version": "${version}",
  "external": false
}

'''
3:24: '",
  "' came as a complete surprise to me
org.stringtemplate.v4.compiler.STException
	at org.stringtemplate.v4.compiler.Compiler.reportMessageAndThrowSTException(Compiler.java:213)
	at org.stringtemplate.v4.compiler.Compiler.compile(Compiler.java:143)
	at org.stringtemplate.v4.STGroup.compile(STGroup.java:448)
	at org.stringtemplate.v4.ST.<init>(ST.java:173)
	at org.clapper.scalasti.STHelper$.apply(ScalastiHelper.scala:8)
	at giter8.G8$.applyTemplate(g8.scala:43)
	at giter8.G8$.write(g8.scala:97)
	at giter8.G8$.write(g8.scala:88)
	at giter8.G8Helpers$$anonfun$write$3$$anonfun$apply$13.apply(g8.scala:325)
	at giter8.G8Helpers$$anonfun$write$3$$anonfun$apply$13.apply(g8.scala:325)
	at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
	at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
	at scala.util.control.Exception$Catch.apply(Exception.scala:102)
	at scala.util.control.Exception$Catch.opt(Exception.scala:118)
	at giter8.G8Helpers$$anonfun$write$3.apply(g8.scala:324)
	at giter8.G8Helpers$$anonfun$write$3.apply(g8.scala:303)
	at scala.collection.immutable.Stream.foreach(Stream.scala:547)
	at giter8.G8Helpers$.write(g8.scala:303)
	at giter8.G8Helpers$$anonfun$giter8$G8Helpers$$applyT$1.apply(g8.scala:169)
	at giter8.G8Helpers$$anonfun$giter8$G8Helpers$$applyT$1.apply(g8.scala:158)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at giter8.G8Helpers$.giter8$G8Helpers$$applyT(g8.scala:158)
	at giter8.G8Helpers$$anonfun$applyTemplate$2.apply(g8.scala:185)
	at giter8.G8Helpers$$anonfun$applyTemplate$2.apply(g8.scala:185)
	at giter8.Apply$$anonfun$inspect$1.apply(apply.scala:51)
	at giter8.Apply$$anonfun$inspect$1.apply(apply.scala:50)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at giter8.Apply$class.inspect(apply.scala:50)
	at giter8.Giter8.inspect(giter8.scala:3)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:22)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:18)
	at scala.Option.map(Option.scala:145)
	at giter8.Giter8.run(giter8.scala:18)
	at giter8.Giter8$.main(giter8.scala:92)
	at giter8.Giter8.main(giter8.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at xsbt.boot.PlainApplication.run(PlainApplication.scala:18)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: org.stringtemplate.v4.compiler.STException
'''

**Comment by eed3si9n** [comment]
You need to escape `\$`.

**Comment by billstephens** [comment]
OF course... Is this for any other use of '$'?

**Comment by eed3si9n** [comment]
`$` is used for templating like $name$.
