### ISSUE TITLE
 .check(substring("' came as a complete surprise to me

### ISSUE THREAD

**Issue by aidylewis** [foundweekends/giter8#214]
I am have giter8 template [here](https://github.com/aidylewis/gatling-sbt.g8). However when I try to install it, I receive an exception that I don't believe is very clear. Do you have any idea on what the cause is?  Thanks

```
$ g8 aidylewis/gatling-sbt.g8
name [gatling-load-tests]: temp
organization [uk.co.bbc]:
27:24: '")
      .check(substring("' came as a complete surprise to me
org.stringtemplate.v4.compiler.STException
        at org.stringtemplate.v4.compiler.Compiler.reportMessageAndThrowSTException(Compiler.java:213)
        at org.stringtemplate.v4.compiler.Compiler.compile(Compiler.java:143)
        at org.stringtemplate.v4.STGroup.compile(STGroup.java:448)
        at org.stringtemplate.v4.ST.<init>(ST.java:173)
        at org.clapper.scalasti.STHelper$.apply(ScalastiHelper.scala:8)
        at giter8.G8$.applyTemplate(g8.scala:43)
        at giter8.G8$.write(g8.scala:97)
        at giter8.G8$.write(g8.scala:88)
        at giter8.G8Helpers$$anonfun$write$3$$anonfun$apply$13.apply(g8.scala:325)
        at giter8.G8Helpers$$anonfun$write$3$$anonfun$apply$13.apply(g8.scala:325)
        at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
        at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
        at scala.util.control.Exception$Catch.apply(Exception.scala:102)
        at scala.util.control.Exception$Catch.opt(Exception.scala:118)
        at giter8.G8Helpers$$anonfun$write$3.apply(g8.scala:324)
        at giter8.G8Helpers$$anonfun$write$3.apply(g8.scala:303)
```

**Comment by xuwei-k** [comment]
`ComputerWorld.scala` contains the `$` charactor. You can exclude `ComputerWorld.scala` use `verbatim`

http://www.foundweekends.org/giter8/template.html#verbatim+field

```diff
--- a/src/main/g8/default.properties
+++ b/src/main/g8/default.properties
@@ -1,2 +1,3 @@
 name=gatling-load-tests
 organization=uk.co.bbc
+verbatim=ComputerWorld.scala
```

**Comment by aidylewis** [comment]
@xuwei-k Many thanks for your help.
