### ISSUE TITLE
Initial template failed, git not found

### ISSUE THREAD

**Issue by markhuyong** [foundweekends/giter8#229]
apple@:~/TempPlace% g8 --version
g8 0.7.1

error log:

```
apple:~/TempPlace% g8 softprops/unfiltered.g8
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at giter8.JgitHelper$.clone(JgitHelper.scala:114)
	at giter8.JgitHelper$.run(JgitHelper.scala:65)
	at giter8.JgitHelper$.run(JgitHelper.scala:78)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:34)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:33)
	at scala.Option.map(Option.scala:145)
	at giter8.Giter8.run(giter8.scala:33)
	at giter8.Giter8.run(giter8.scala:25)
	at giter8.Giter8.run(giter8.scala:20)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
**Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException:** git://github.com/softprops/unfiltered.g8.git: not found.
	at org.eclipse.jgit.transport.BasePackConnection.noRepository(BasePackConnection.java:263)
	at org.eclipse.jgit.transport.BasePackConnection.readAdvertisedRefsImpl(BasePackConnection.java:198)
	at org.eclipse.jgit.transport.BasePackConnection.readAdvertisedRefs(BasePackConnection.java:176)
	at org.eclipse.jgit.transport.TransportGitAnon$TcpFetchConnection.<init>(TransportGitAnon.java:194)
	at org.eclipse.jgit.transport.TransportGitAnon.openFetch(TransportGitAnon.java:120)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 20 more
**Error during sbt execution: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin**
```

**Comment by TonioGela** [comment]
Closed since the repo's last commit is in 2012, it uses deprecated functions like `ls()`.
