### ISSUE TITLE
Improved logging needed

### ISSUE THREAD

**Issue by billstephens** [foundweekends/giter8#230]
I'm trying to decipher an issue with a template, but the logging leaves a lot to be desired. I have no clue what 10:137 is referring to.  

`$ g8 file:///Users/bstephens/Projects/Connectors/connector-template-java.v8 
**10:137: doesn't look like an expression**
org.stringtemplate.v4.compiler.STException
	at org.stringtemplate.v4.compiler.Compiler.reportMessageAndThrowSTException(Compiler.java:213)
	at org.stringtemplate.v4.compiler.Compiler.compile(Compiler.java:143)
	at org.stringtemplate.v4.STGroup.compile(STGroup.java:448)`

**Comment by billstephens** [comment]
It was a jar file in the template.  verbatim fixed it. Had to revert a ton of template files to work back the the issue.
