### ISSUE TITLE
Refactoring altered the semantics

### ISSUE THREAD

**Issue by cunei** [foundweekends/giter8#282]
The refactoring in #277 seems to have significantly changed the behavior of Giter8. Here is an example:
In an empty directory:
```
$ cat default.properties 
name = builder
$ cat aFile 
Hello, $name$ $surname$.
```
Now, compare 0.7.2, and the current 0.7.x post-refactoring.
0.7.2:
```
$ g8 --name=prox file://../empty/
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024M; support was removed in 8.0

Exiting due to error in the template
File: /tmp/giter8-940816499576680/aFile, context [anonymous] 1:14 internal error: org.stringtemplate.v4.compiler.STException: context [anonymous] 1:14 attribute surname isn't defined
        at giter8.G8$STErrorHandler.runTimeError(g8.scala:110)
        at giter8.G8$STErrorHandler.runTimeError(g8.scala:105)
        at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:133)
```
But with the refactored code:
```
$ g8 --name=prox file://../empty
name [prox]:

Template applied in ./prox
$ find prox -type f
$
```
So:
1) the non-interactive behavior turned into interactive: the value passed on the command line is used as a default, but it still stops
2) on my machine, at least, the blinking cursor appears not on the "name [prox]:" line but underneath, on a separate line
3) expansions of unknown parameters no longer lead to an error message, but appear to succeed, except the generated directory is empty.

Similarly, calling `applyTemplate()` directly also does not produce an error, and silently produces an empty directory.

**Comment by eed3si9n** [comment]
Seems more like regressions /cc @foxmk

**Comment by foxmk** [comment]
Those are definitely regressions, I'll check it out

**Comment by cunei** [comment]
As an addendum, when calling `applyTemplate()`, the parameters that are not defined via `additionalProperties` are substituted with an empty string, rather than the defaults from `default.properties`.

**Comment by eed3si9n** [comment]
We need a stable version of Giter8 with Toni (@cunei)'s changes soon,
so why don't we branch of existing `0.7.x` as `0.8.x` branch, wipe out the history prior to refactoring and backport https://github.com/foundweekends/giter8/pull/278/files?

**Comment by cunei** [comment]
I actually changed my client code in order to use the new `applyTemplate()`, which fits quite perfectly our use case. It might be preferable to just move forward with a fix, if possible.

**Comment by foxmk** [comment]
I'll finish fixes on Saturday. You can take a look at https://github.com/foxmk/giter8/tree/issue-282-regresssion-fixes (WIP)

**Comment by eed3si9n** [comment]
Cool. Thanks for quick turnaround.

**Comment by foxmk** [comment]
@cunei Unfortunately I couldn't reproduce bug with `additionalProperties`. Can you provide more info, please?

**Comment by cunei** [comment]
@foxmk, I did more investigations, and in the end it was just a combination of the issues already listed above, plus another bug in another piece of software. I checked your fixes, and all seems ok. Thanks!

**Comment by fabriziofortino** [comment]
@eed3si9n I am experiencing the same error with the latest version (0.9.x branch). Below the whole stack. Can this be a regression?

```
Exiting due to error in the template
File: /var/folders/22/g7d85p4j2cx7bj3sf2mb0tg489wxn0/T/giter8-1338692998854856/akka-http/src/main/g8/api/api.json, context [anonymous] 13:19 internal error: org.stringtemplate.v4.compiler.STException: context [anonymous] 13:19 attribute description isn't defined
        at giter8.G8$STErrorHandler.runTimeError(g8.scala:117)
        at giter8.G8$STErrorHandler.runTimeError(g8.scala:112)
        at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:133)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:193)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.ST.write(ST.java:427)
        at org.stringtemplate.v4.ST.render(ST.java:497)
        at org.clapper.scalasti.ST.render(ST.scala:285)
        at giter8.G8$.applyTemplate(g8.scala:109)
        at giter8.G8$.write(g8.scala:160)
        at giter8.G8$.write(g8.scala:145)
        at giter8.G8$$anonfun$writeTemplates$2$$anonfun$apply$11.apply(g8.scala:424)
        at giter8.G8$$anonfun$writeTemplates$2$$anonfun$apply$11.apply(g8.scala:424)
        at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
        at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
        at scala.util.control.Exception$Catch.apply(Exception.scala:102)
        at scala.util.control.Exception$Catch.opt(Exception.scala:118)
        at giter8.G8$$anonfun$writeTemplates$2.apply(g8.scala:423)
        at giter8.G8$$anonfun$writeTemplates$2.apply(g8.scala:413)
        at scala.collection.immutable.Stream.foreach(Stream.scala:547)
        at giter8.G8$.writeTemplates(g8.scala:413)
        at giter8.G8$$anonfun$applyT$1.apply(g8.scala:272)
        at giter8.G8$$anonfun$applyT$1.apply(g8.scala:265)
        at scala.util.Either$RightProjection.flatMap(Either.scala:523)
        at giter8.G8$.applyT(g8.scala:265)
        at giter8.G8$.fromDirectory(g8.scala:62)
        at giter8.G8TemplateRenderer$.render(TemplateRenderer.scala:34)
        at giter8.JgitHelper$$anonfun$run$1$$anonfun$apply$2.apply(JgitHelper.scala:64)
        at giter8.JgitHelper$$anonfun$run$1$$anonfun$apply$2.apply(JgitHelper.scala:60)
        at giter8.JgitHelper$flatMapMonad.flatMap(JgitHelper.scala:42)
        at giter8.JgitHelper$$anonfun$run$1.apply(JgitHelper.scala:60)
        at giter8.JgitHelper$$anonfun$run$1.apply(JgitHelper.scala:59)
        at giter8.JgitHelper$flatMapMonad.flatMap(JgitHelper.scala:42)
        at giter8.JgitHelper.run(JgitHelper.scala:59)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:39)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:38)
        at scala.Option.map(Option.scala:145)
        at giter8.Giter8.run(giter8.scala:38)
        at giter8.Giter8.run(giter8.scala:54)
        at giter8.Giter8$.main(giter8.scala:116)
        at giter8.Giter8.main(giter8.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.Run.invokeMain(Run.scala:67)
        at sbt.Run.run0(Run.scala:61)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:84)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by eed3si9n** [comment]
@fabriziofortino probably. Please open a new issue with repro steps.
