### ISSUE TITLE
Difficult to install

### ISSUE THREAD

**Issue by eythor** [foundweekends/giter8#301]
Hello, i'm new to java, scala and sbt. I was installing g8 via the instructions, but I kept getting bombarded with NoClassDefFoundError. I thought this might be an issue, but if it isn't maybe you can tell me what's wrong with my current installation.

Scala version:
```
Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL
```
Java version:
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

Following the installation instructions: 
```
eythor@eythor-ubuntu:~$ curl https://raw.githubusercontent.com/foundweekends/conscript/master/setup.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1693  100  1693    0     0   2460      0 --:--:-- --:--:-- --:--:--  2464
Fetching current launch configuration...
--2017-05-26 16:43:34--  https://raw.githubusercontent.com/foundweekends/conscript/master/src/main/conscript/cs/launchconfig
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 332 [text/plain]
Saving to: ‘/home/eythor/.conscript/foundweekends/conscript/cs/launchconfig’

/home/eythor/.conscript/fou 100%[===========================================>]     332  --.-KB/s    in 0s      

2017-05-26 16:43:35 (24,2 MB/s) - ‘/home/eythor/.conscript/foundweekends/conscript/cs/launchconfig’ saved [332/332]

Fetching launcher...
--2017-05-26 16:43:35--  https://oss.sonatype.org/content/repositories/public/org/scala-sbt/launcher/1.0.0/launcher-1.0.0.jar
Resolving oss.sonatype.org (oss.sonatype.org)... 107.23.166.173, 52.22.249.229
Connecting to oss.sonatype.org (oss.sonatype.org)|107.23.166.173|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1197598 (1,1M) [application/java-archive]
Saving to: ‘/home/eythor/.conscript/launcher-1.0.0.jar’

/home/eythor/.conscript/lau 100%[===========================================>]   1,14M   374KB/s    in 3,1s    

2017-05-26 16:43:38 (374 KB/s) - ‘/home/eythor/.conscript/launcher-1.0.0.jar’ saved [1197598/1197598]

conscript installed to /home/eythor/.conscript/bin/cs
Getting org.foundweekends.conscript conscript_2.11 0.5.1 ...
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        1 artifacts copied, 0 already retrieved (271kB/6ms)
Getting Scala 2.11.8 (for conscript)...
:: retrieving :: org.scala-sbt#boot-scala
        confs: [default]
        6 artifacts copied, 0 already retrieved (26456kB/20ms)
java.lang.NoClassDefFoundError: scopt/OptionParser
        at conscript.Conscript.run(conscript.scala:160)
        at conscript.Conscript.run(conscript.scala:158)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: scopt.OptionParser
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 11 more
Error during sbt execution: java.lang.NoClassDefFoundError: scopt/OptionParser
```

I issued a find looking for "scopt*jar" anywhere on the file system and found a few, then I copied one such jar into the lib folder within .conscripts boot directy like so: 
```
eythor@eythor-ubuntu:~/.conscript$ cp ~/.ivy2/cache/com.github.scopt/scopt_2.11/jars/scopt_2.11-3.4.0.jar ~/.conscipt/boot/scala-2.11.8/lib
```
Just gives me another NoClassDefFoundError for dispatch/Http$

```
eythor@eythor-ubuntu:~/.conscript$ ./bin/cs 
java.lang.NoClassDefFoundError: dispatch/Http$
        at conscript.Conscript$.<init>(conscript.scala:10)
        at conscript.Conscript$.<clinit>(conscript.scala)
        at conscript.Conscript.run(conscript.scala:160)
        at conscript.Conscript.run(conscript.scala:158)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: dispatch.Http$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
Error during sbt execution: java.lang.NoClassDefFoundError: dispatch/Http$
```
So I did the same thing repeatedly for dispatch-core, async-http-client, slf4j and finally netty. All of them were found in the ~/.ivy2/cache/ directory. And eventually, I managed to run ~/.conscript/bin/cs.

But then I get the error:
```
eythor@eythor-ubuntu:~$ cs foundweekends/giter8
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
An unexpected error occurred: Please check your internet connection.
Exception message: net/liftweb/json/JsonParser$
```

**Comment by eed3si9n** [comment]
As documented in http://www.foundweekends.org/giter8/, modern version of sbt such as sbt 0.13.16 supports `new` command, which is able to invoke Giter8, so I suggest you give that a try.
