### ISSUE TITLE
Error in sbt-giter8 when using sbt 1.2.6

### ISSUE THREAD

**Issue by sebastianvoss** [foundweekends/giter8#406]
When using the latest sbt version (`1.2.6`) the `sbt-giter8` plugin (`0.11.0` and `0.12.0-M1`) throws an error and crashes the the sbt session:

```
[info] Loading settings for project microservice-g8 from build.sbt ...
[error] References to undefined settings: 
[error] 
[error]   scriptedLaunchOpts from Test / g8Test ((giter8.Giter8Plugin.giter8TestSettings) Giter8Plugin.scala:102)
[error] 
[error]   scriptedBufferLog from Test / g8Test ((giter8.Giter8Plugin.giter8TestSettings) Giter8Plugin.scala:102)
[error]      Did you mean Test / g8 / scriptedBufferLog ?
[error] 
[error]   scriptedLaunchOpts from scripted ((sbt.ScriptedPlugin.projectSettings) ScriptedPlugin.scala:87)
[error] 
[error]   scriptedBufferLog from scripted ((sbt.ScriptedPlugin.projectSettings) ScriptedPlugin.scala:87)
[error]      Did you mean Test / g8 / scriptedBufferLog ?
[error]  
[error] 	at sbt.internal.util.Init.Uninitialized(Settings.scala:360)
[error] 	at sbt.internal.util.Init.Uninitialized$(Settings.scala:347)
[error] 	at sbt.Def$.Uninitialized(Def.scala:20)
[error] 	at sbt.internal.util.Init.delegate(Settings.scala:260)
[error] 	at sbt.internal.util.Init.delegate$(Settings.scala:236)
[error] 	at sbt.Def$.delegate(Def.scala:20)
[error] 	at sbt.internal.util.Init.compiled(Settings.scala:194)
[error] 	at sbt.internal.util.Init.compiled$(Settings.scala:182)
[error] 	at sbt.Def$.compiled(Def.scala:20)
[error] 	at sbt.internal.util.Init.make(Settings.scala:204)
[error] 	at sbt.internal.util.Init.make$(Settings.scala:199)
[error] 	at sbt.Def$.make(Def.scala:20)
[error] 	at sbt.internal.Load$.$anonfun$apply$5(Load.scala:266)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:261)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] References to undefined settings: 
[error] 
[error]   scriptedLaunchOpts from Test / g8Test ((giter8.Giter8Plugin.giter8TestSettings) Giter8Plugin.scala:102)
[error] 
[error]   scriptedBufferLog from Test / g8Test ((giter8.Giter8Plugin.giter8TestSettings) Giter8Plugin.scala:102)
[error]      Did you mean Test / g8 / scriptedBufferLog ?
[error] 
[error]   scriptedLaunchOpts from scripted ((sbt.ScriptedPlugin.projectSettings) ScriptedPlugin.scala:87)
[error] 
[error]   scriptedBufferLog from scripted ((sbt.ScriptedPlugin.projectSettings) ScriptedPlugin.scala:87)
[error]      Did you mean Test / g8 / scriptedBufferLog ?
[error]  
[error] Use 'last' for the full log.
```

**Comment by xuwei-k** [comment]
see https://github.com/foundweekends/giter8.g8/pull/15/files

**Comment by eed3si9n** [comment]
Here's another example of the same workaround - https://github.com/scala/scala-seed.g8/pull/30/commits/6bafe82dc7dfe34f5729c48afa268af161f070b7
I just sent #412 that should fix this.

**Comment by xuwei-k** [comment]
0.12.0-M2 released
