### ISSUE TITLE
Release 0.13.1 broken?

### ISSUE THREAD

**Issue by alexandru** [foundweekends/giter8#472]
Attempting an update to 0.13.1 [breaks the build](https://github.com/alexandru/typelevel-library.g8/pull/66/checks?check_run_id=813672357):

```
[info] welcome to sbt 1.3.12 (Azul Systems, Inc. Java 1.8.0_252)
[info] loading settings for project typelevel-library-g8-build from plugins.sbt,giter8.sbt ...
[info] loading project definition from /home/runner/work/typelevel-library.g8/typelevel-library.g8/project
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.foundweekends.giter8:sbt-giter8:0.13.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.foundweekends.giter8:sbt-giter8;sbtVersion=1.0;scalaVersion=2.12:0.13.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/foundweekends/giter8/sbt-giter8_2.12_1.0/0.13.1/sbt-giter8-0.13.1.pom
[error]   not found: /home/runner/.ivy2/local/org.foundweekends.giter8/sbt-giter8/scala_2.12/sbt_1.0/0.13.1/ivys/ivy.xml
[error]   unauthorized: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8/scala_2.12/sbt_1.0/0.13.1/ivys/ivy.xml (Bintray)
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8/scala_2.12/sbt_1.0/0.13.1/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
```

Is something wrong with this release?

**Comment by eed3si9n** [comment]
```
[error]   unauthorized: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8/scala_2.12/sbt_1.0/0.13.1/ivys/ivy.xml (Bintray)
```

ugh. Maybe this is another Bintray issue.

**Comment by eed3si9n** [comment]
This should be fixed now.
